In [1]:
import pandas as pd
import numpy as np
from math import sqrt
import matplotlib.pyplot as plt
import collections
import xlsxwriter 

In [2]:
#import data set
products_df = pd.read_csv('part_bdml_data.csv')
products_df.head(10)

customerId                        products
0           0                              20
1           1  2|2|23|68|68|111|29|86|107|152
2           2       111|107|29|11|11|11|33|23
3           3                         164|227
4           5                             2|2
5           6                  144|144|55|266
6           7                     135|206|259
7           8                       79|8|8|48
8           9                     102|2|2|297
9          10                   84|77|290|260

In [3]:
#Split the values
products_df['products'] = products_df.products.str.split('|')

In [4]:
x=products_df['products'] 
x

0                                             [20]
1        [2, 2, 23, 68, 68, 111, 29, 86, 107, 152]
2               [111, 107, 29, 11, 11, 11, 33, 23]
3                                       [164, 227]
4                                           [2, 2]
5                              [144, 144, 55, 266]
6                                  [135, 206, 259]
7                                   [79, 8, 8, 48]
8                                 [102, 2, 2, 297]
9                               [84, 77, 290, 260]
10                                  [25, 127, 127]
11                        [18, 183, 287, 172, 289]
12                                  [79, 8, 8, 38]
13                              [2, 2, 20, 20, 20]
14                                      [251, 143]
15                                             [2]
16                     [49, 49, 49, 279, 279, 279]
17                                       [70, 135]
18                                         [48, 8]
19      [20, 20, 20, 281, 281, 

In [5]:
#Checking to convert frequency as ratings
p=pd.value_counts(x[0])
p

20    1
dtype: int64

In [6]:
#Checking index
y=p.index
y    

Index(['20'], dtype='object')

In [7]:
#Make rating matrics
a = (80,300)
b=np.zeros(a)

In [8]:
#Saving Customer ID
z=products_df['customerId'] 
z

0       0
1       1
2       2
3       3
4       5
5       6
6       7
7       8
8       9
9      10
10     11
11     12
12     13
13     14
14     15
15     16
16     17
17     18
18     19
19     20
20     21
21     22
22     23
23     24
24     25
25     28
26     29
27     30
28     32
29     33
     ... 
50     57
51     58
52     59
53     60
54     61
55     65
56     66
57     67
58     68
59     70
60     71
61     72
62     73
63     76
64     78
65     79
66     80
67     81
68     87
69     89
70     90
71     91
72     93
73     94
74     95
75     96
76     97
77     98
78     99
79    100
Name: customerId, Length: 80, dtype: int64

In [9]:
#Make customer ID and ratings of products

for i in range(0,80):
    p=pd.value_counts(x[i])
    y=p.index
    for k in range(0,80):
        b[k,0]=z[k]
        for j in range(0,y.size):
            b[i,(int(y[j])+1)]=p[j]
        
print(b)        
    
b=b.T  

[[  0.   0.   0. ...   0.   0.   0.]
 [  1.   0.   0. ...   0.   0.   0.]
 [  2.   0.   0. ...   0.   0.   0.]
 ...
 [ 98.   0.   0. ...   0.   0.   0.]
 [ 99.   0.   0. ...   0.   0.   0.]
 [100.   3.   0. ...   0.   0.   0.]]


In [10]:
#Delete customer ID 
inputs=np.delete(b,0,0)

In [11]:
#Find the similarity matrics and make diagonal as 0
from sklearn.metrics.pairwise import cosine_similarity
output = cosine_similarity(inputs)
np.fill_diagonal(output, 0 )
ratings=np.dot(output,inputs)


In [12]:
#Make a for loop for all the product ID
l=list(range(0,299))

In [13]:
#Make Weighted matrics
def user(x):
    m=ratings[:,x]
    o=np.vstack([l,m])
    o=o.T
    v=o[o[:,1].argsort()[::-1]]
    print(type(v))
    return v[:,0]


In [14]:
# Find final answer for user 7
answer_final=list((user(7)))
type(answer_final[0])


<class 'numpy.ndarray'>


numpy.float64

In [15]:
#Previous Product ID 
q=(x[7])
list_set = set(q) 
q = (list(list_set))
q

['48', '8', '79']

In [16]:
#Mamke product ID to integeer
answer_final = [int(i) for i in answer_final] 
answer_final = list(map(int, answer_final))
answer_final

[48,
 79,
 38,
 8,
 264,
 36,
 23,
 41,
 11,
 104,
 99,
 100,
 101,
 102,
 103,
 298,
 105,
 98,
 107,
 108,
 109,
 110,
 106,
 96,
 97,
 95,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 111,
 114,
 112,
 113,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 131,
 130,
 129,
 120,
 77,
 115,
 116,
 117,
 118,
 119,
 121,
 128,
 122,
 123,
 124,
 125,
 126,
 127,
 78,
 73,
 76,
 28,
 21,
 22,
 24,
 25,
 26,
 27,
 29,
 19,
 30,
 31,
 32,
 33,
 34,
 35,
 20,
 18,
 75,
 7,
 1,
 2,
 3,
 4,
 5,
 6,
 9,
 17,
 10,
 12,
 13,
 14,
 15,
 16,
 37,
 39,
 40,
 67,
 61,
 62,
 63,
 64,
 65,
 66,
 68,
 42,
 69,
 70,
 71,
 72,
 148,
 74,
 60,
 59,
 58,
 57,
 56,
 55,
 54,
 53,
 52,
 51,
 50,
 49,
 47,
 46,
 45,
 44,
 43,
 147,
 149,
 297,
 242,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 243,
 241,
 150,
 240,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237

In [17]:
#Delete Previous product for suggession
from collections import OrderedDict
x = OrderedDict.fromkeys(answer_final)
y = OrderedDict.fromkeys(q)

In [18]:
for k in x:
    if k in y:
        x=x.pop(k)
        
x=(list(x))

In [19]:
#Show some suggession
for i in range(0,10):
    print (x[i])



48
79
38
8
264
36
23
41
11
104
